### PR TITLE
Add Universal compatibility

### LINKED ISSUE #5: Is not safe for universal rendering
Every window access should be guarded

### PR DESCRIPTION
**Pull request by ludoblues**
Fix #5

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@ludoblues thank you for this great PR!
I'll review and test it asap and let you know. As this comes with a couple of breaking changes if we merge it I'll publish the code as `v1.0.0` to avoid conflicts

**Comment by ludoblues** [comment]
@FrancescoCioria exact, it would be a semver major update.

Basically, there are 2 major changes:

1. We switch the cookie library to another one that abstract the client and server side.

2. We invert the relationship between react-cookie-banner and the app that use it, in a way that this is not react-cookie-banner that (can) provide the cookie library to the parent app anymore, but the opposite (to strengthen the singleton usage of the cookie API in server side).

**Comment by radufarcas10** [comment]
Hi @FrancescoCioria. Any news on the v1.0.0 with this fix?

**Comment by giogonzo** [comment]
Just released v2.0.0 with support for server side rendering
Please see the updated docs in https://github.com/buildo/react-cookie-banner#server-side-rendering-universal and let us know how it works for you!

Closing this

**Pull request closed without merging**
