### PR TITLE
#41: Server side rendering issues (closes #41)

### LINKED ISSUE #41: Server side rendering issues
Hi guys, can we merge the waiting pull request to use react-cookies with SSR?

Currently having invalid checksum issues with server side rendering.

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #41

### tests performed
- examples work without errors/warnings
- the cookie of the first examples "accepts-cookies" is correctly stored in the browser (verified with devtools)

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by adomrockie** [comment]
Looks good to me so far, will pull to local dev and test with our code.

**Comment by adomrockie** [comment]
Getting can't resolve error 'aws-sdk'.

**Comment by giogonzo** [comment]
Hi @adomrockie, installing straight from github, npm will not "build" this package first. That's why it isn't working out of the box.

You'd need to clone this repository, checkout the correct branch, install the dependencies, and then, from your project, install the package locally using `npm i path/to/react-cookie-banner`

To simplify this, I've released a temporary version that you can install with `npm i react-cookie-banner@universal`. Let me know if this helps! :)

**Comment by giogonzo** [comment]
@adomrockie @FrancescoCioria tested myself on a server-rendered project, I can confirm the annoying warning is gone! Just added a missing re-export in the last commit

@adomrockie going to merge this and release in a few minutes

**Comment by adomrockie** [comment]
Installs fine and works with no changes with current code base, I have two cookie cards ie BetaCard and CookieBannerCard components


The error I am now  getting is 

> `Call to Node module failed with error: TypeError: __WEBPACK_IMPORTED_MODULE_10_react_cookie_banner__.Cookies is not a constructor`

**Comment by FrancescoCioria** [comment]
how are you importing `Cookies` in your code?

**Comment by radufarcas10** [comment]
Hi guys!

I was using `react-cookie-banner@0.0.17` in a isomorphic app and was getting the checksum error from React that the code on the server doesn't match the one from client and after I updated to `react-cookie-banner@3.0.0` and I'm getting this error:

`In Promise Error TypeError: (0 , _reactCookieBanner.cookie) is not a function
    at new CookieBanner (/src/js/components/cookie-banner.js:15:16)`

I'm importing the Cookies as explained in the updated docs.
Any idea why I'm getting this?

**Comment by FrancescoCioria** [comment]
yes, from your error it looks like you're importing and using the function `cookie`, which is longer exported.

from `2.0.0+`, you should import the class `Cookies` and use that one to manipulate cookies as described in the readme: https://github.com/buildo/react-cookie-banner#server-side-rendering-aka-universal.

**Comment by radufarcas10** [comment]
I'm actually importing the class `Cookies` like in the readme:

`import React, { Component } from 'react';
import { Cookies, CookiesProvider, CookieBannerUniversal } from 'react-cookie-banner';

class CookieBanner extends Component {
  static displayName = 'cookie-banner';

 const cookies = new Cookies();

  constructor(props) {
    super(props);

    this.state = {
      visible: cookies.get('__imoac') !== 'true'
    };

    this.setHidden = this.setHidden.bind(this);
  }

  setHidden() {
    cookies.set('__imoac');
    this.setState({ visible: false });
  }

  render() {
    const { visible } = this.state;

    return (
      <CookiesProvider cookies={cookies}>
      <CookieBannerUniversal         
        className={`section-cookies ${visible ? '' : 'hide'}`}
        disableStyle={true}
        dismissOnScroll={false}
        onAccept={this.setHidden}
      />
      </CookiesProvider>
    );
  }
}

export default CookieBanner;`

**Comment by FrancescoCioria** [comment]
> `In Promise Error TypeError: (0 , _reactCookieBanner.cookie`

Here it's written clearly that, in your transpiled code, you're doing something like `require(react-cookie-banner).cookie(...)`

Did you correctly re-build you project after upgrading `react-cookie-banner`? I suggest you try a clean install + build:
```
rm -rf node_modules
npm i
npm run build
```

**Comment by radufarcas10** [comment]
Yes, sorry, I forgot to re-build. But now, after re-build I'm getting an error saying that the cookies are not defined:

`In Promise Error ReferenceError: cookies is not defined
    at new CookieBanner (/src/js/components/cookie-banner.js:20:16)`

**Comment by FrancescoCioria** [comment]
@radufarcas10 simply read the error :)

> `In Promise Error ReferenceError: cookies is not defined at new CookieBanner (/src/js/components/cookie-banner.js:20:16)`

The variable `cookies` inside `/src/js/components/cookie-banner.js` at the line `20` position `16` is not defined.
Again, this is an error in your code, not in the library. In particular, by looking at the code you pasted previously, you should change your component like this:

```js
class CookieBanner extends Component {
  static displayName = 'cookie-banner';
  cookies: new Cookies()
```

and then call it in your functions as `this.cookies`. the `this` is necessary.

**Pull request merged**
